### ISSUE TITLE
Flash plugin not found though other plugins in folder are read

### ISSUE THREAD

**Issue by faasie** [tiliado/nuvolaplayer#332] opened 2017-05-02 20:18 UTC
OS: OpenSUSE 42.2
Debian package converted via Alien -r converter.
Nuvola v.3.0.8

When I launch either Spotify app or Amazon Music app (only tried these two) player indicates that no flash player is found.

Relevant --debug output:
```
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Trying to play /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Pipeline state changed from NULL to READY.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: Pipeline state changed from PAUSED to PLAYING.
Runner: [DEBUG    Nuvola] FormatSupport.vala:110: End of stream for file /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: IcedTea-Web Plugin (using IcedTea-Web 1.6.2 (suse-1.6.2-x86_64)) (enabled, not flash) at /usr/lib64/browser-plugins/javaplugin.so: The <a href="http://icedtea.classpath.org/wiki/IcedTea-Web">IcedTea-Web Plugin</a> executes Java applets.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: GNOME Shell Integration (enabled, not flash) at /usr/lib64/browser-plugins/libgnome-shell-browser-plugin.so: This plugin provides integration with GNOME Shell for live extension enabling and disabling. It can be used only by extensions.gnome.org
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Evince Browser Plugin (enabled, not flash) at /usr/lib64/browser-plugins/libevbrowserplugin.so: The <a href="http://wiki.gnome.org/Apps/Evince/">Evince</a> 3.20.1 plugin handles documents inside the browser window.
Runner: [WARNING  Nuvola] FormatSupportCheck.vala:152: No Flash plugin has been found.
Runner: [DEBUG    Nuvola] WebAppWindow.vala:170: Sidebar position: 947
```

Output of `/usr/lib64/browser-plugins`:
```
➜  ~ ls -l /usr/lib64/browser-plugins 
total 116
lrwxrwxrwx 1 root root    28 Apr 30 17:22 javaplugin.so -> /etc/alternatives/javaplugin
-rwxr-xr-x 1 root root 87104 Sep  4  2016 libevbrowserplugin.so
lrwxrwxrwx 1 root root    41 Apr 29 22:29 libflashplayer.so -> /usr/lib64/flash-plugin/libflashplayer.so
-rwxr-xr-x 1 root root 18976 Jan 16 06:23 libgnome-shell-browser-plugin.so
➜  ~ 
```

Installed `Flash`:
```
➜  ~ sudo zypper search -i flash       
Loading repository data...
Reading installed packages...

S | Name         | Summary                  | Type   
--+--------------+--------------------------+--------
i | flash-plugin | Adobe Flash Player NPAPI | package
➜  ~ 
```

Nuvola Player info:
```
➜  ~ nuvolaplayer3 -V   
Nuvola Player 3 3.0.8
Revision 683fc7254443f13a35e4ba33d948ca6e382e690f
WebKitGTK 2.12.5
libsoup 2.54.1
➜  ~ 
```

**Comment by fenryxo** [comment] 2017-05-02 21:34
Hello @faasie. Is WebKitPluginProcess2 installed? Run `find /usr -name WebKitPluginProcess2` to check it. If there is no hit, install a package with this file.

Btw, I'm going to add official support of openSUSE this or the next month tiliado/nuvolaplayer#7.

**Comment by faasie** [comment] 2017-05-03 01:35
@fenryxo 
Hmm. Per OpenSUSE forums:
WebKitPluginProcess2 has been removed/disabled recently.
From webkit2gtk3's changelog:
```
Mon Apr 25 14:28:33 UTC 2016 - zaitor@opensuse.org
  
- Drop pkgconfig(gtk+-2.0) BuildRequires and pass
  -DENABLE_PLUGIN_PROCESS_GTK2=OFF to configure. We do no longer
  ship the flash-plugin in openSUSE, and it were the last consumer
  of this functionality. This also have the added bonus of freeing
  zenity and dependant packages of gtk2 dependencies.  
```
So, that being said, it looks like I should look at either Flatpak (and a Patron account ;-) ) or wait until the official OpenSUSE build; though I'm curious how that will work given the above info...

**Comment by fenryxo** [comment] 2017-05-03 10:45
Just to clear any confusion, there will be no official openSUSE builds. The official openSUSE support means that

* I verify that Flatpaks can be installed and work on openSUSE.
* Step-by-step installation instructions for openSUSE  are included in the [Nuvola Apps Repository Index](https://nuvola.tiliado.eu/).
* The default openSUSE theme is included in the flatpaks.

It may seem simple but there is a lot of work behind it.

Anyway, I'm closing this issue as the problem is in OpenSUSE's packaging of WebKitGTK.

**Closed by fenryxo** 2017-05-03 10:45 UTC
