### ISSUE TITLE
Spotify login error [expires 2017-05-20]

### ISSUE THREAD

**Issue by dbogdanov** [tiliado/nuvolaplayer#309] opened 2017-03-01 11:41 UTC
I got this error on login screen for Spotify:

```
Integration error

Failed to inject JavaScript API. Function 'Nuvola.core.emit' failed. file:///usr/share/nuvolaplayer3/web_apps/spotify/integrate.js:112: TypeError: undefined is not an object (evaluating 'window.Spotify.Shuttle._initContext')

The application might not function properly.
```

![screenshot from 2017-03-01 12-37-59](https://cloud.githubusercontent.com/assets/409668/23458343/3a7a6618-fe7c-11e6-894d-b2c2f87a9ba0.png)

```
nuvolaplayer3 -V
Nuvola Player 3 3.0.5
Revision 743bb1dd10654eeee68a8682c72f15ece6d7baf6
WebKitGTK 2.14.5
libsoup 2.52.2
```

**Comment by fenryxo** [comment] 2017-03-02 20:38
Hello @dbogdanov. Thanks for taking the time to report this issue. Spotify behaves faulty in Nuvola since the Flash 10 → 12 update. I still haven't any clue why that happens.

**Comment by fenryxo** [comment] 2017-04-20 08:33
Hello @dbogdanov. Is the issue reproducible with the latest [Flash 25.0.0.148](https://get.adobe.com/flashplayer/)?

**Comment by fenryxo** [comment] 2017-05-06 20:16
And with the latest stable webkitgtk 2.16.1?

**Comment by fenryxo** [comment] 2017-05-22 15:02
Hello @dbogdanov. I'm closing this issue as I haven't received any response to my request for more information I posted on April 20th, 2016. If the issue still persists, feel free to add missing information to reopen this ticket.

**Closed by fenryxo** 2017-05-22 15:02 UTC
Labels: bug, more info required
