### ISSUE TITLE
Cannot access any of the options in the "gear" menu

### ISSUE THREAD

**Issue by emacsomancer** [tiliado/nuvolaplayer#179] opened 2015-11-03 23:58 UTC
Nothing opens for me in the "gear" menu.  In particular I was trying to access preferences in order to turn pop-up notifications off.

OS: x86_64 Arch Linux - 03.11.2015 up-to-date
Nuvola version: 5.8 (from Arch AUR [git])
##

**Comment by fenryxo** [comment] 2015-11-04 19:27
Hello. Thanks for taking the time to report your issue. AUR builds are sometimes tricky. Could you try to uninstall nuvolaplayer-git and diorite-git packages completely and then reinstall nuvolaplayer-git package? If it won't help, I need more information to investigate it further: 

* Debugging output from terminal up to the point you have clicked the Gear button.
* What desktop environment do you use?

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

> Nuvola version: 5.8 (from Arch AUR [git])

Actually, you probably have Nuvola Player 3.0  & Google Play Music script 5.8, not Nuvola 5.8.

**Comment by emacsomancer** [comment] 2015-11-04 20:01
Yes, sorry about mixing up the google play music script version no. & the nuvolaplayer number.  Completely uninstalled nuvolaplayer-git and diorite-git and the googlemusicplay script and reinstalled. Behaviour is same.

Debugging output #1 (clicked on "test", and also tried clicking on all of the items within the gear menu): https://gist.github.com/emacsomancer/1e54aae4ac01460313c6

Debugging output #2 (clicked on "googleplay" and then tried clicking on all of the items within the gear menu): https://gist.github.com/emacsomancer/39d9cf3934f40fe630c8

I can click the gear menu and see all of the items, but none of them do anything when i click them.

I'm using AwesomeWM as windows manager with compton as the compositor.

**Comment by fenryxo** [comment] 2015-11-04 20:38
There might be a bug in GTK. Do these GLib critical warnings occur before or after you click the gear button? 

```
[Runner:CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
[Runner:CRITICAL  GLib] Application will not function properly.
[Runner:CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
[Runner:CRITICAL  GLib] Application will not function properly.
```

**Comment by fenryxo** [comment] 2015-11-04 20:39
Or  before/after you click any menu item in gear menu?

**Comment by emacsomancer** [comment] 2015-11-04 21:03
Those errors message seem to occur when I actually open up Google Play Music.

When I click the gear itself, or any of the items within the gear menu, I don't get any messages from "nuvolaplayer3 --debug" in the terminal.

**Comment by fenryxo** [comment] 2015-11-07 10:05
If you run `nuvolaplayer3 --debug`, you should see Services selector window, which has also a gear menu. Does this menu also fail to trigger any action?

**Comment by emacsomancer** [comment] 2015-11-07 16:18
> If you run `nuvolaplayer3 --debug`, you should see Services selector window, which has also a gear menu. Does this menu also fail to trigger any action?

yes, that menu also fails to trigger any action no matter which menu
item I try clicking on.

**Comment by wedens** [comment] 2015-11-10 06:07
I don't have any of this problems with Nuvola Player 3.0 on Arch

**Comment by fenryxo** [comment] 2015-11-10 12:32
> I don't have any of this problems with Nuvola Player 3.0 on Arch (installed from aur -git)

That's interesting. Can you see error messages like in comment https://github.com/tiliado/nuvolaplayer/issues/179#issuecomment-153855425 in your debugging output?

**Comment by wedens** [comment] 2015-11-11 05:57
@fenryxo yes. I can see this messages

**Comment by emacsomancer** [comment] 2015-11-11 06:12
@fenryxo I'm using AwesomeWM as my windows manager (no DE, just compton for compositing). Do you think there's some gnome dependency I'm missing? (Generally I don't have problems with either GTK or QT-based apps.)

As a stopgap - are there text configuration files I can manually edit to stop notifications from popping up on track change?

**Comment by fenryxo** [comment] 2015-11-11 09:08
> I'm using AwesomeWM as my windows manager (no DE, just compton for compositing). Do you think there's some gnome dependency I'm missing?

Honestly, I have no clue what's wrong.


> As a stopgap - are there text configuration files I can manually edit to stop notifications from popping up on track change?

You can try to open preferences from command line: `nuvolaplayer3ctl action preferences` or edit configuration file directly, e.g.:

```
cat ~/.config/nuvolaplayer3/apps_data/deezer/config.json 
{
 ...
  "component" : {
    ...
    "notifications" : {
      "enabled" : false
    },
    ...
  },
  ...
}
```

**Comment by emacsomancer** [comment] 2015-11-11 15:02
I don't seem to have `deezer` directory in `~/.config/nuvolaplayer3/apps_data/ ....

**Comment by fenryxo** [comment] 2015-11-11 16:06
You can create it. Make sure to replace "deezer" with the id of service you actually use ;-)

**Comment by fenryxo** [comment] 2015-11-19 14:07
I regret to tell you that I've decided to postpone this issue because of insufficient resources. While I'd love to make Nuvola Player work everywhere without any issues, it is not possible with current project funding and it's especially difficult to support Arch Linux because almost any instance is unique. Thanks for your understanding.

**Comment by fenryxo** [comment] 2017-04-10 11:44
Hello @emacsomancer. I'm closing this issue as I cannot reproduce it with Nuvola 3.1.2.

The [Nuvola project now officially supports Arch Linux since Nuvola 3.1 Milestone 2 thanks to cross-distribution flatpak packages](https://medium.com/nuvola-news/nuvola-3-1-milestone-2-deprecates-deb-rpm-packages-in-favor-of-flatpaks-and-officially-supports-579534c3b75c). These are not meant to replace AUR builds but to provide an alternative way to install Nuvola for those users who are not, for whatever reason, satisfied with the Arch way of installation. I believe that [Flatpak builds of Nuvola are a huge step forward because Flatpak finally, after years of struggling, allows Nuvola project to pursue its goals](https://medium.com/nuvola-news/how-the-benefits-of-nuvola-flatpak-builds-outweigh-the-drawbacks-c2ea5fde867c).

Note that Nuvola 3.1 is currently available only to users with [Premium/Patron plan](https://tiliado.eu/nuvolaplayer/funding/) but this will change with the Nuvola 4.0 release later this year.

Best regards,

Jiri Janousek, Nuvola core developer

**Closed by fenryxo** 2017-04-10 11:44 UTC
Labels: bug, postponed
