### ISSUE TITLE
Back button on deezer player doesnt remember scroll position of Album page.

### ISSUE THREAD

**Issue by johann50** [tiliado/nuvolaplayer#755] opened 2021-07-20 19:56 UTC
If I'm somewhere on the album page and I go to another page,
and then use the back button to go back to the album page, it goes
to the top of the album page instead of going to where I was before.

**Comment by fenryxo** [comment] 2021-07-24 20:09
Hello @johann50, thanks for reporting the issue.

Nuvola seems to behave the same as Firefox. Firefox also does not remember page position on history navigation, while Chrome does. I'm not sure what is the cause of this problem though.

**Comment by johann50** [comment] 2021-07-25 03:58
This problem only occurs only if the back page is the Album page.
Other types of pages appear to work fine.

Also, this problem does NOT occur in the Tidal Player.

It DOES occur for the Qobuz player with respect to the 'Favorites' page.

**Comment by jiri-janousek** [comment] 2022-01-23 13:10
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.

**Closed by jiri-janousek** 2022-01-23 13:10 UTC
Labels: type: bug
