### ISSUE TITLE
[BUG] Plex Music script from Flathub doesn't play anything on KDE

### ISSUE THREAD

**Issue by kuriot** [tiliado/nuvolaplayer#631] opened 2020-09-08 01:06 UTC
Linux distribution and its version: Manjaro Linux 20.1  
Desktop environment: KDE Plasma 5.19.4 (KDE frameworks 5.73.0)  
Nuvola Runtime version: 4.16.44 (44-g4f7864a) (flatpak) 
Plex Music script: 1.5.0 (0-ge41e59d) (flatpak)

### Describe the bug

It doesn't remember settings (not Nuvola, but Plex itself) and doesn't play any media - gives a error dialog with "Try again" and "Skip" buttons.

**Steps to reproduce the behavior**

1. Go to Discover and install from flathub 'Nuvola App Servie' and 'Plex Nuvola App'.
2. Launch Plex Music and enter your Plex instance address.
3. Try to play anything. Also, go to Plex settings, change anything, relaunch app and see that settings were not saved.

**Expected behavior**

Expect it to play media and save settings. 

**Debugging log**

When launched from cli, I see errors:

```
$ LC_ALL=C /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=nuvola-app-plex eu.tiliado.NuvolaAppPlex
Gtk-Message: 03:59:37.539: Failed to load module "appmenu-gtk-module"
Runner: [WARNING Δ534752us Nuvola] StartupWindow.vala:146: tiliado-account-message: Features Tier: Free
Your system is broken: dlsym doesn't work! This has been reported to be caused by Nvidia's libGL. You should expect time related functions to misbehave. https://bugs.chromium.org/p/chromium/issues/detail?id=16800
[0908/035938.177145:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.
[0908/035938.209590:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
Worker: [DEBUG Δ004728us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Worker: [DEBUG Δ001584us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
Worker: [DEBUG Δ010493us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000126us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Worker: [DEBUG Δ013815us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ000056us CefGtk] RendererContext.vala:57: JS Context created 1
Worker: [DEBUG Δ004763us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Worker: [DEBUG Δ001447us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
Worker: [DEBUG Δ008884us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000127us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Worker: [DEBUG Δ004871us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ003359us CefGtk] RendererContext.vala:57: JS Context created 1
Worker: [DEBUG Δ112574us Nuvola] CefRendererExtension.vala:145: Lost JS context
Worker: [INFO Δ000039us CefGtk] RendererContext.vala:64: JS Context released: 1
[0908/035938.879227:WARNING:spdy_session.cc(3326)] Received HEADERS for invalid stream 1
[0908/035939.713039:ERROR:object_proxy.cc(619)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd5: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0908/035939.713096:ERROR:kwallet_dbus.cc(100)] Error contacting kwalletd5 (isEnabled)
[0908/035939.713710:ERROR:object_proxy.cc(619)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0908/035939.713752:ERROR:kwallet_dbus.cc(72)] Error contacting klauncher to start kwalletd5
[0908/035939.714113:ERROR:object_proxy.cc(619)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd5: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[0908/035939.714141:ERROR:kwallet_dbus.cc(414)] Error contacting kwalletd5 (close)
```

**Additional context**

Wanted to try and install from AUR, but it can't find all dependencies.

**Comment by fenryxo** [comment] 2020-09-09 20:20
Hello @kuriot, thanks for your bug report. Are both issues (not able to play music and save settings) reproducible also in Chrome/Chromium/Firefox web browsers? 

This line looks suspicions but I'm not sure where it comes from:

```
[0908/035938.879227:WARNING:spdy_session.cc(3326)] Received HEADERS for invalid stream 1
```

**Comment by kuriot** [comment] 2020-09-10 14:56
No, I use Plex via Firefox normally and in Chrome it also works: both saving and playing.

**Comment by fenryxo** [comment] 2020-09-10 15:34
Hm, I'm afraid I cannot be fixed until #583 is done.

**Comment by kuriot** [comment] 2020-09-10 16:12
Thanks for the information. I will stick to Plex in Firefox and Tidal via Nuvola for now, then.

**Comment by trustin** [comment] 2021-03-04 12:38
Looks like Plex calls `window.navigator.mediaSession.setActionHandler("stop", this.onCloseShortcut))`, but the CEF Nuvola Player is currently using is not up-to-date enough to understand `"stop"` enum value. I'm curious what will happen if we override `window.navigator.mediaSession.setActionHandler()`, so that it does nothing when `"stop"` is given.

**Comment by trustin** [comment] 2021-03-04 13:05
By the way, if this is something that can't be fixed in short term, how about removing Plex Music from the supported app list? Some people might feel it deceptive, although I'm OK to find it later because I paid for other apps and thought Plex Music support as a bonus.

**Comment by fenryxo** [comment] 2021-03-04 21:28
Indeed, we should deprecate Plex and remove it from our homepage.

**Comment by jiri-janousek** [comment] 2022-01-08 08:38
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.

**Closed by jiri-janousek** 2022-01-08 08:38 UTC
Labels: type: bug, QtWebEngine port
