### ISSUE TITLE
Menu items in app indicator are being duplicated every time the music starts or unpauses

### ISSUE THREAD

**Issue by oktayacikalin** [tiliado/nuvolaplayer#776] opened 2021-11-22 00:45 UTC
### Basic information

- Nuvola Player version: 4.23.0 (0-g3ab9c9a)
- The streaming service you use and its version: YouTube Music 1.6.0 (0-gd8bd7f0)
- $ lsb_release -a
No LSB modules are available.
Distributor ID:	Elementary
Description:	elementary OS 6 Odin
Release:	6
Codename:	odin
- $ uname -m
x86_64
- $ flatpak run eu.tiliado.NuvolaAppYoutubeMusic  --version
YouTube Music script
Version: 1.6.0
Revision: 0-gd8bd7f0
Maintainer: Jiří Janoušek

--- Powered by ---

Nuvola Player - Genuine flatpak build
Version 4.23.0
Revision 0-g3ab9c9a
Diorite 4.23.0
Chromium 75.0.3770.100
ValaCEF 75.3770.16
libsoup 2.72.0
- Desktop environment is the default one (Pantheon)
- Installed flatpaks:
eu.tiliado.Nuvola
eu.tiliado.NuvolaAppAudible
eu.tiliado.NuvolaAppSoundcloud
eu.tiliado.NuvolaAppTunein
eu.tiliado.NuvolaAppYoutube
eu.tiliado.NuvolaAppYoutubeMusic

### Describe the bug

- Open YT Music script
- Play a song
- Menu items are being duplicated
- Pause
- Unpause
- Menu items are being duplicated
- Seems to loop endlessly

![Bildschirmfoto von 2021-11-22 01-36-43](https://user-images.githubusercontent.com/687189/142785879-81a6f32f-05c6-4aec-8089-ed284baba6bd.png)
![Bildschirmfoto von 2021-11-22 01-36-55](https://user-images.githubusercontent.com/687189/142785883-e85368ff-3ee9-4d42-a8ab-6374bb5150d5.png)
[nuvola-debug.txt](https://github.com/tiliado/nuvolaplayer/files/7577501/nuvola-debug.txt)
[nuvola-youtube-music-debug.txt](https://github.com/tiliado/nuvolaplayer/files/7577503/nuvola-youtube-music-debug.txt)

**Comment by jiri-janousek** [comment] 2021-11-22 20:25
Hello @oktayacikalin, thanks for reporting the issue. I'll look at it at the weekend.

**Comment by jiri-janousek** [comment] 2021-11-27 11:56
Hello @oktayacikalin, it seems elementaryos no longer supports appindicators out of the box. How did you enable them?

**Comment by oktayacikalin** [comment] 2021-11-27 12:16
Hi @jiri-janousek, I think I installed this one:

https://github.com/Lafydev/wingpanel-indicator-ayatana#:~:text=libwingpanel%2D2.0%2Ddev-,version%20odin(6)%20%3A,-sudo%20apt%2Dget

And now I have the following as an autostart item configured:

![image](https://user-images.githubusercontent.com/687189/143680944-8bdce543-fb47-4f38-bc4d-f072aea9d118.png)

**Comment by jiri-janousek** [comment] 2021-11-27 12:41
It might be a bug in that particular appindicator implementation. Since other appindicator implementations seem fine and the wingpanel-indicator-ayatana is not supported by elementary os, I'm going to put this issue to backlog until I have more time to investigate it further.

**Comment by oktayacikalin** [comment] 2021-11-28 20:58
In fact elementary OS does not support appindicator and all those other older implementations at all.

Do you have a plan for an implementation which works out of the box?

**Comment by jiri-janousek** [comment] 2021-11-28 21:48
I'm not sure what elementary feature actually replaced appindicators.

**Comment by jiri-janousek** [comment] 2022-01-08 08:14
I'm closing this issue as I believe it is not a bug in Nuvola Player but in a particular app indicator implementation that is not under our control. I don't think there is any alternative in elementaryOS. I think the decision to retire app indicators is unfortunate but there isn't anything I can do with that :-(

**Closed by jiri-janousek** 2022-01-08 08:14 UTC
Labels: type: bug
