### ISSUE TITLE
Nuvola player does not recognize Flash Player plugin on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by Cris70** [tiliado/nuvolaplayer#238] opened 2016-05-30 09:34 UTC
I have been using Nuvola Player v3 on Tumbleweed for a few months to play Deezer.

About a month ago suddenly Nuvola started reporting that no Flash Player plugin was installed.
The Flash Player plugin is indeed installed on my system, in the form of the pepper-flash plugin (and the Fresh Player plugin wrapper for Firefox).

I have never had the plain Flash Player plugin for linux installed: I prefer using pepper-flash as it is more up-to-date and more secure. However, Nuvola never had problems using it previously.

I see that Nuvola is looking for browser plugins in /usr/lib64/browser-plugins/.
This is what I have in that directory:

```
  lrwxrwxrwx 1 root root     28 apr 29 11:16 javaplugin.so -> /etc/alternatives/javaplugin
  -rwxr-xr-x 1 root root 437520 mag  2 23:04 libfreshwrapper-flashplayer.so
  -rwxr-xr-x 1 root root  77048 apr 27 04:38 skypebuttons.so
```

But apparently Nuvola cannot make use of it anymore.

About my system:
Linux openSUSE Tumbleweed (rolling release) 
lsb_release: openSUSE Tumbleweed (20160422) (x86_64)
DE: KDE plasma 5.6.4

Nuvola player:
Version: 3.0.0
Revision: fuzzy (that's what I have in my "About" dialog)

I installed it from here: https://software.opensuse.org/package/nuvolaplayer?search_term=nuvola+player

If you need more information don't hesitate to contact me

**Comment by fenryxo** [comment] 2016-05-30 09:54
Hello @Cris70. Thanks for taking time to report this issue. I need more information to investigate it further. Could you post [a debugging output from terminal as specified in Bug-Reporting-Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output)? Also, version 3.0.0 is no longer supported. You might want to ask the packager to upgrade to version 3.0.2.

**Comment by Cris70** [comment] 2016-05-30 10:31
@fenryxo [here](https://gist.github.com/Cris70/bf080943181697a6f9118958b6dec8d7) is the debugging output.

Also, I'll contact the maintainer to see if he can update the package to release 3.0.2.

**Comment by fenryxo** [comment] 2016-05-30 11:06
It looks as if the `WebKitPluginProcess2` module hasn't been installed on your system. Could you install a package that contains this module? The absolute path is `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitPluginProcess2` in Debian/Ubuntu but it may differ in openSUSE obviously. If you need help, contact support of your distribution or a package maintainer of WebKitGTK library in your distribution.

**Comment by Cris70** [comment] 2016-05-30 14:25
@fenryxo I have the package libwebkit2gtk-4_0-37 installed, which provides these files:

```
libwebkit2gtk-4_0-37 - Library for rendering web content, GTK+ Port

/usr/lib/libwebkit2gtk-4_0-37
/usr/lib/libwebkit2gtk-4_0-37/WebKitDatabaseProcess
/usr/lib/libwebkit2gtk-4_0-37/WebKitNetworkProcess
/usr/lib/libwebkit2gtk-4_0-37/WebKitPluginProcess
/usr/lib/libwebkit2gtk-4_0-37/WebKitWebProcess
/usr/lib64/libwebkit2gtk-4.0.so.37
/usr/lib64/libwebkit2gtk-4.0.so.37.13.8

7 files total
```

I think this is what you're referring to, isn't it?

**Comment by fenryxo** [comment] 2016-05-30 14:54
No, it isn't. I cannot see `WebKitPluginProcess2` in your list.

**Comment by Cris70** [comment] 2016-06-01 07:21
@fenryxo I asled for support on the openSUSE forums, because I found evidence that WebKitPluginProcess2 should have been in the libwebkit2gtk-4_0-37 package.

Unfortunately, their reply is not what I would have expected/liked:

> WebKitPluginProcess2 has been removed/disabled recently.
> From webkit2gtk3's changelog:
> 
> ```
> Mon Apr 25 14:28:33 UTC 2016 - zaitor@opensuse.org
>   
> - Drop pkgconfig(gtk+-2.0) BuildRequires and pass
>   -DENABLE_PLUGIN_PROCESS_GTK2=OFF to configure. We do no longer
>   ship the flash-plugin in openSUSE, and it were the last consumer
>   of this functionality. This also have the added bonus of freeing
>   zenity and dependant packages of gtk2 dependencies.
> ```

> 
>> Does this mean that there's no possibility to have Deezer on Nuvola Player correctly working on openSUSE?
> >Unfortunately Deezer insists in using Flash :-(
> 
> As Nuvola Player uses WebKit2GTK3, yes.


I guess you can mark this bug as closed :-(

**Comment by fenryxo** [comment] 2016-06-01 07:50
You could try to fill a bug report against the openSUSE's  `libwebkit2gtk-4_0-37` package and ask them to enable WebKitPluginProcess2 again and move the WebKitPluginProcess2 executable to a separate `libwebkit2gtk-4_0-37-gtk2` package. As a result, the main `libwebkit2gtk-4_0-37` package will still be without any GTK+ 2 dependencies and users who need Flash could be able to install the GTK+ 2 dependent  `libwebkit2gtk-4_0-37-gtk2` package. Fedora, Debian and Ubuntu do that exactly.

> We do no longer ship the flash-plugin in openSUSE, and it were the last consumer of this functionality.

Well, the maintainer should realize that users still may want to use Flash even if it is no longer shipped by openSUSE.

Anyway, I'm closing this issue as invalid because the bug is in openSUSE's WebKitGTK+ build.

**Closed** 2016-06-01 07:51 UTC
Labels: invalid

**Comment by hurricanehrndz** [comment] 2016-11-04 16:57
@Cris70 

You can find an update nuvolaplayer for Tumbleweed here:
https://build.opensuse.org/project/show/home:hurricanehernandez

**Comment by Cris70** [comment] 2016-11-05 10:22
@hurricanehrndz  Hey, thank you very much!
Unfortunately I have a problem of circular reference (I am not sure it is correct to report it here, but don't know where to report it):

```
cris@PolariSuse:~/Downloads> sudo zypper in ./nuvolaplayer-3.1.0+git.1477861492.3bec14d-5.1.x86_64.rpm ./diorite-0.3.1+git.1477862300.8b81cb8-4.1.x86_64.rpm ./nuvola-app-spotify-2.2+git.1472307415.1828d92-3.1.noarch.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...
2 Problems:
Problem: nothing provides nuvola-app-spotfiy needed by nuvolaplayer-3.1.0+git.1477861492.3bec14d-5.1.x86_64
Problem: nuvola-app-spotify-2.2+git.1472307415.1828d92-3.1.noarch requires nuvolaplayer, but this requirement cannot be provided
```
Why does NuvolaPlayer requires nuvola-app-spotify? Shouldn't it be an optional component?

**Comment by hurricanehrndz** [comment] 2016-11-05 12:59
Thanks. I will fix that.

**Comment by hurricanehrndz** [comment] 2016-11-05 16:30
@cris70,

A new build was just triggered to fix the circular reference. Currently the
only Nuvola app available in my repo is the spotify one. Is there a specific app you
are looking for? I will ensure to place it at the top of my TODO list.

Thanks for the feed back again.

On Sat, Nov 05, 2016 at 03:22:36AM -0700, Cristiano Guadagnino wrote:
> @hurricanehrndz  Hey, thank you very much!
> Unfortunately I have a problem of circular reference (I am not sure it is correct to report it here, but don't know where to report it):
> 
> ```
> cris@PolariSuse:~/Downloads> sudo zypper in ./nuvolaplayer-3.1.0+git.1477861492.3bec14d-5.1.x86_64.rpm ./diorite-0.3.1+git.1477862300.8b81cb8-4.1.x86_64.rpm ./nuvola-app-spotify-2.2+git.1472307415.1828d92-3.1.noarch.rpm
> Loading repository data...
> Reading installed packages...
> Resolving package dependencies...
> 2 Problems:
> Problem: nothing provides nuvola-app-spotfiy needed by nuvolaplayer-3.1.0+git.1477861492.3bec14d-5.1.x86_64
> Problem: nuvola-app-spotify-2.2+git.1472307415.1828d92-3.1.noarch requires nuvolaplayer, but this requirement cannot be provided
> ```
> Why does NuvolaPlayer requires nuvola-app-spotify? Shouldn't it be an optional component?
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/tiliado/nuvolaplayer/issues/238#issuecomment-258602897

-- 
Best Regards,
Carlos Hernandez
4096R / 2CDA 09D6 3EE3 2885 623B  1268 9864 FE7A 97C3 D526
https://sks-keyservers.net/pks/lookup?op=vindex&search=0x9864FE7A97C3D526

**Comment by Cris70** [comment] 2016-11-07 08:48
@hurricanehrndz 
I am using the Deezer app. It would be very nice if you could add it.
Thank you for your support!!!

**Comment by flavio** [comment] 2016-12-01 12:50
Sorry for bringing up this issue again...

@hurricanehrndz I just upgraded to openSUSE 42.2 and I stumbled over this bug (this time it's spotify that complains about the lack of a flash plugin).

I guess everything is caused by libwebkit2gtk-4_0-37 as described a couple of comments above.

Is there any workaround/fix?

**Comment by hurricanehrndz** [comment] 2016-12-01 14:00
@flavio 

I was able to fix Tumbleweed builds when they created webkit2gtk3-plugin-process-gtk2 package. It contains the WebKitPluginProcess2 module that was removed from the main libwebkit2gtk package.

I could enable openSUSE 42.2 in my repo and see what happens if you like.

**Comment by flavio** [comment] 2016-12-01 14:27
@hurricanehrndz that would be nice. If that works we can request the package to be added to 42.2

**Comment by hurricanehrndz** [comment] 2016-12-01 21:48
@flavio, @Cris70 

As you requested https://build.opensuse.org/project/show/home:hurricanehernandez:nuvolaplayer3k

@Cris70 sorry for the delay.

**Comment by Cris70** [comment] 2016-12-01 21:58
No problem @hurricanehrndz  ;-)

**Comment by hurricanehrndz** [comment] 2016-12-01 22:01
PS I'm not involved with this project. I do use openSUSE products heavily though and this is my way of giving back.

**Comment by hurricanehrndz** [comment] 2016-12-01 22:15
@Cris70 

PS deezer gets stuck on loading for me not sure if you will have the same experience.

**Comment by hurricanehrndz** [comment] 2016-12-01 22:59
@Cris70 

I created an issue here:
https://github.com/tiliado/nuvola-app-deezer/issues/8

If you wait long enough it seems deezer eventually loads.

**Comment by flavio** [comment] 2016-12-02 20:40
@hurricanehrndz thanks for your help, unfortunately there's no package on openSUSE 42.2 that provides `webkit2gtk3-plugin-process-gtk2`:

```
2 Problems:
Problem: nothing provides webkit2gtk3-plugin-process-gtk2 needed by nuvolaplayer-3.1.0+git.1480180912.a84bbaf-2.1.x86_64
Problem: nothing provides webkit2gtk3-plugin-process-gtk2 needed by nuvolaplayer-3.1.0+git.1480180912.a84bbaf-2.1.x86_64

Problem: nothing provides webkit2gtk3-plugin-process-gtk2 needed by nuvolaplayer-3.1.0+git.1480180912.a84bbaf-2.1.x86_64
 Solution 1: keep obsolete nuvolaplayer-3.0.2-1.4.x86_64
 Solution 2: break nuvolaplayer-3.1.0+git.1480180912.a84bbaf-2.1.x86_64 by ignoring some of its dependencies
```

How is that fixed on tumbleweed, did someone created that sub-package?

**Comment by hurricanehrndz** [comment] 2016-12-02 22:21
Official package in Factory creates the subpackage:
https://build.opensuse.org/package/view_file/openSUSE:Factory/webkit2gtk3/webkit2gtk3.spec?expand=1

**Comment by flavio** [comment] 2016-12-05 10:55
@hurricanehrndz: thanks for your help. I submitted this bug on openSUSE's bugzilla https://bugzilla.suse.com/show_bug.cgi?id=1013631
