### ISSUE TITLE
MPRIS integration not working properly on Ubuntu 16.04

### ISSUE THREAD

**Issue by mramiro** [tiliado/nuvolaplayer#224] opened 2016-04-27 17:01 UTC
**This issue has been fixed in the [master](https://github.com/tiliado/nuvolaplayer) & [3.0.x](https://github.com/tiliado/nuvolaplayer/tree/3.0.x) GIT branches. Thanks for your bug report.**

At first, this fix will be available with the next rebuilt of packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). Later, the fix will be also included in the next bug-fix release of the [Nuvola Player 3.0 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html). **Update:** The fix has been released in Nuvola Player 3.0.3.

---

**Original bug report:**

Ever since I updated to Ubuntu 16.04, the "Play" button on Unity's sound indicator widget stopped working properly. When I click on the "Play" button it triggers the event and playback starts, but it looks like the "can-pause" flag doesn't get raised (or is overridden by a "can-play" flag, according to the log below) because the button never becomes a "Pause" button. Pressing it again does nothing and thus the only way for me to stop playback is going the the nuvola app itself and clicking the pause button.

The indicator works as expected when using another audio player (tried with Rhytmbox and Audacious). Media control events (sending XF86AudioPlay) work just fine.

Also, it seems that this issue is limited to Ubuntu 16.04, since it is not present on another machine I have that's running Ubuntu 15.10

System specs:
```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial

> uname -m
x86_64

> nuvolaplayer3 --version
Nuvola Player 3 3.0.1
Revision 7440d9b357eaf4895c7303f52d0f1ce3fa920613

> apt-cache policy nuvolaplayer3
nuvolaplayer3:
  Instalados: 3.0.1-0+1~xenial
  Candidato:  3.0.1-0+1~xenial
  Tabla de versión:
 *** 3.0.1-0+1~xenial 500
        500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 Packages
        100 /var/lib/dpkg/status

> nuvolaplayer3 --debug -a google_play_music
Master: [DEBUG      Gtk] Connecting to session manager
Master: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: compiz (null), CSD 0, appmenu 1, menubar 1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.12
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Groove at /usr/share/nuvolaplayer3/web_apps/groove, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SoundCloud at /usr/share/nuvolaplayer3/web_apps/soundcloud, version 1.1
Master: [INFO     Nuvola] WebAppRegistry.vala:89: Using web app Google Play Music, version 5.12, data dir /usr/share/nuvolaplayer3/web_apps/google_play_music
Master: [DEBUG    Nuvola] MasterController.vala:463: Launch app runner for 'google_play_music': /usr/lib/nuvolaplayer3/apprunner -D -a /usr/share/nuvolaplayer3/web_apps/google_play_music 
Master: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
Runner: [DEBUG      Gtk] Connecting to session manager
Runner: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: compiz (null), CSD 0, appmenu 1, menubar 1
Runner: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
Master: [DEBUG    Nuvola] MasterController.vala:287: Connected to runner server for 'google_play_music'.
Runner: [DEBUG    Nuvola] Connection.vala:132: Network Proxy: system settings
Runner: [DEBUG    Nuvola] WebEngine.vala:65: Nuvola WebKit Extension directory: /usr/lib/nuvolaplayer3
Runner: [WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
Runner: [DEBUG    Nuvola] Notifications.vala:175: Notifications: persistence false, actions false, icons false
Master: [DEBUG    Nuvola] MediaKeys.vala:99: GNOME settings daemon appeared: org.gnome.SettingsDaemon, :1.15
Runner: [DEBUG    Nuvola] MPRISProvider.vala:73: Bus acquired: org.mpris.MediaPlayer2.NuvolaAppGooglePlayMusic, registering objects
Runner: [DEBUG    Nuvola] MPRISProvider.vala:90: Bus name acquired: org.mpris.MediaPlayer2.NuvolaAppGooglePlayMusic
Worker: [DEBUG    Nuvola] WebExtension.vala:237: Page 1 created for (null)
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://play.google.com/music/listen#/now, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Trying to play /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from NULL to READY.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from PAUSED to PLAYING.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: End of stream for file /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Shockwave Flash (enabled, flash) at /usr/lib/mozilla/plugins/flashplugin-alternative.so: Shockwave Flash 11.2 r202
Runner: [DEBUG    Nuvola] WebAppWindow.vala:170: Sidebar position: 951
Worker: [DEBUG    Nuvola] WebExtension.vala:140: Window object cleared: https://play.google.com/music/listen#/now, 0x561c60645370, 0x561c60599b20, 0x7f6925c2f740
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e14ece20
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e14efec0
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e14f0300
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e157f800
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e1584a40
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e1587b60
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://fls.doubleclick.net/activityi;src=2542116;type=andro238;cat=googl515;ord=1;num=9021255075931.549?, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: https://play-music.gstatic.com/fe/bbe4245a86314191d500936b201735f1/webcomponents-lite.min.js:11:20001: CONSOLE ERROR Refused to get unsafe header "Location"
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e1582700
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e1508b00
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e14f1260
Runner: [DEBUG     Json] Copying immutable JsonNode 0x5575e15835a0
Runner: [INFO     Nuvola] AppRunnerController.vala:236: Logged in as  ()
Runner: https://play-music.gstatic.com/fe/bbe4245a86314191d500936b201735f1/sj_srcs.js:21582:13: CONSOLE WARN This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
https://play-music.gstatic.com/fe/bbe4245a86314191d500936b201735f1/sj_srcs.js:21583:13: CONSOLE WARN This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://2542116.fls.doubleclick.net/activityi;src=2542116;type=andro238;cat=googl515;ord=1;num=9021255075931.549, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fplay.google.com&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.oVMKCZSUkzc.O%2Fm%3D__features__%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-diW2z34601i9eG0Nx2FzzG4t8QA#rpctoken=439739116&forcesecure=1, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://0.client-channel.google.com/client-channel/client?cfg=%7B%222%22%3A%22music%22%2C%228%22%3Afalse%2C%2213%22%3Afalse%7D&ctype=music&xpc=%7B%22cn%22%3A%22C2IZvROPM3%22%2C%22tp%22%3Anull%2C%22osh%22%3Anull%2C%22ppu%22%3A%22https%3A%2F%2Fplay.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.client-channel.google.com%2Frobots.txt%22%7D, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://clients4.google.com/invalidation/lcs/client?xpc=%7B%22cn%22%3A%22wbO6gw2iuF%22%2C%22tp%22%3Anull%2C%22osh%22%3Anull%2C%22ppu%22%3A%22https%3A%2F%2Fplay.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2Fclients4.google.com%2Frobots.txt%22%7D, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://play.google.com/music/services/streamingloadalltracks?u=0&xt=CjUKATASMEFNLVdiWGkzcDB3b2RjS0pUUVgyVXpVYUJ6cmhxQnByVGc6MTQ2MTc3NTg2MjU1OQ%3D%3D&json=%7B%22tier%22%3A2%2C%22requestCause%22%3A1%2C%22requestType%22%3A1%2C%22sessionId%22%3A%22ix9h8xkjdv7t%22%7D&format=jsarray, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-pause
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-stop
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-play
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-previous
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-next
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Vector smash protection is enabled.
Runner: Failed to open VDPAU backend libvdpau_va_gl.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
Runner: Failed to open VDPAU backend libvdpau_va_gl.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
Runner: https://www.googleadservices.com/pagead/conversion.js:20:112: CONSOLE ERROR Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
Runner: https://www.googleadservices.com/pagead/conversion.js:20:258: CONSOLE ERROR Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
Runner: [DEBUG    Nuvola] WebEngine.vala:462: Navigation, current window: uri = https://plus.google.com/u/0/_/notifications/frame?sourceid=166&hl=es-419&origin=https%3A%2F%2Fplay.google.com&uc=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.oVMKCZSUkzc.O%2Fm%3D__features__%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-diW2z34601i9eG0Nx2FzzG4t8QA#pid=166&rpctoken=324364984&_methods=onError%2ConInfo%2ChideNotificationWidget%2CpostSharedMessage%2Creauth%2CsetNotificationWidgetHeight%2CsetNotificationWidgetSize%2CswitchTo%2CnavigateTo%2CsetNotificationText%2CsetNotificationAnimation%2CgetNotificationText%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart&id=I1_1461775869399&parent=https%3A%2F%2Fplay.google.com&pfname=, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-play
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: file:///usr/share/nuvolaplayer3/js/main.js:350:16: CONSOLE LOG JS API: Action activated: toggle-play
Runner: [DEBUG    DioriteGtk] actionsregistry.vala:325: Action activated: playback/win.toggle-play(null)
Runner: [DEBUG    Nuvola] LyricsProvider.vala:103: Fetcher: NuvolaLyricsFetcherCache
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] LyricsProvider.vala:115: Fetch error: Song I Got a Feelin (Just Nineteen) was not found in cache
Runner: [DEBUG    Nuvola] LyricsProvider.vala:103: Fetcher: NuvolaAZLyricsFetcher
Runner: [DEBUG    Nuvola] LyricsProvider.vala:115: Fetch error: Song I Got a Feelin (Just Nineteen) was not found on AZ Lyrics
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-pause
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-stop
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-play
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-previous
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-next
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
```

**Comment by fenryxo** [comment] 2016-04-29 18:55
Hello @mramiro. Thanks for taking the time to report this issue. I believe there is a bug in the Unity Sound indicator widget as all MPRIS metadata are set correctly by Nuvola Player (see the picture). I'll report the issue upstream when I get the chance.

![ubuntu_16 04_mpris_bug](https://cloud.githubusercontent.com/assets/853706/14926380/360c8ee2-0e4c-11e6-840c-56c8441c4752.png)

**Comment by fenryxo** [comment] 2016-04-30 18:36
Reported upstream as [indicator-sound bug 1576970](https://bugs.launchpad.net/ubuntu/+source/indicator-sound/+bug/1576970).

**Comment by bartlibert** [comment] 2016-05-02 12:57
The same issue is present with the new built-in media control in gnome-shell 3.20. Now, I'm not an MPRIS expert, but according to the info linked below, CanPlay should be true if a track is playing, which is not the case in NuvolaPlayer. In VLC for example, it is set to true while playing. VLC is thus perfectly controllable from the gnome-shell, while NuvolaPlayer is not.

Reference: https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanPlay

**Comment by mramiro** [comment] 2016-05-02 23:26
Thanks for your support, @fenryxo. So, after taking a look at the MPRIS specification provided by @bartlibert, I think he's is right. I just checked with Rhythmbox and d-feet tells me it does almost the same thing VLC does:

1. It sets `CanPlay` to true when there's possible to start playback (which is always, since I think Rhythmbox just starts playing your whole library on shuffle if there's no item selected), regardless of the playback status.
2. It also sets `CanPause` to true always, though to me this isn't right, as per the MPRIS spec (you're supposed to set it to true only when there's a  "current track" and it can be paused). But the sound indicator doesn't seem to care about it.

So, as it seems Nuvola Player isn't implementing the spec correctly. Maybe it changed recently, or maybe the interface in the previous Ubuntu versions weren't strict enough... I don't know.

Anyway, I started messing around with the Google Play integration script and I found out that if you set `canPlay` and `canPause` to true always, the indicator works again. But as that seemed kind of hackish to me I forked the repo and fixed the script so that it follows what (I think) the spec says. [Here's the commit](https://github.com/mramiro/nuvola-app-google-play-music/commit/e510e365e9bdd19170c6466ec23087db52618131)

I've been testing it for a while and it seems to work alright. I hadn't created a pull request because I thought maybe this is something that should be fixed in the Nuvola Player engine itself, since it affects more than one nuvola app (maybe all, since I only confirmed the issue is present in Google Play and Spotify), but if you want, I can create one.

Regards.

**Comment by regisz** [comment] 2016-05-03 13:22
here same issue with Spotify (the player Control menu is inactive too)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

$ uname -m
x86_64

$ nuvolaplayer3 --version
Nuvola Player 3 3.0.2
Revision 438080394af3bb92c2f403d9fd3ae76a60e98cb1
WebKitGTK 2.10.9

$ apt-cache policy nuvolaplayer3
nuvolaplayer3:
  Telepítve: 3.0.2-0+1~xenial
  Jelölt:    3.0.2-0+1~xenial
  Verziótáblázat:
 *** 3.0.2-0+1~xenial 500
        500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 Packages
        100 /var/lib/dpkg/status

**Comment by fenryxo** [comment] 2016-05-03 19:57
You're right. The implementation of the MPRIS spec in Nuvola Player is wrong.

The issue has been fixed in the git master branch and in the packages of Nuvola Player 3.1 Rolling Releases. Later, the fix will be also included in an upcoming Nuvola Player 3.0.3 Stable Release unless a regression is found. Thanks for your bug report.

**Comment by fenryxo** [comment] 2016-05-09 09:24
Due to insufficient funds, release 3.0.3 is postponed to early June.

**Comment by fenryxo** [comment] 2016-06-05 07:10
The fix has been released in Nuvola Player 3.0.3. Thanks for your bug report.

**Closed by fenryxo** 2016-06-05 07:10 UTC
Labels: bug, in progress

**Comment by regisz** [comment] 2016-06-06 05:22
I updated to Nuvola Player 3.0.3 , bug has been stayed. After I switched to 3.1.0 but this bug has not been fixed :(.

$ nuvolaplayer3 --version
Nuvola Player R 3.1.0+201606030904.5cece9e
Revision 5cece9ef6ec58fb6365fce7e24d260cbd24fa006
WebKitGTK 2.10.9
libsoup 2.52.2

$ apt-cache policy nuvolaplayer3
nuvolaplayer3:
  Telepítve: 3.1.0~201606030904.5cece9e-0+1~xenial
  Jelölt:    3.1.0~201606030904.5cece9e-0+1~xenial
  Verziótáblázat:
 *** 3.1.0~201606030904.5cece9e-0+1~xenial 500
        500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/devel amd64 Packages
        100 /var/lib/dpkg/status

**Comment by regisz** [comment] 2016-06-06 08:15
Hm, in 1 case it was good, but I can not reproduce this good state.

**Comment by regisz** [comment] 2016-06-06 08:19
I have some critical log item, I put here, maybe these are the same issue, I do not know:

```
Runner: [WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
Worker: [DEBUG    Nuvola] WebExtension.vala:220: Page 1 created for (null)
Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded about:loading
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Worker: [DEBUG    Nuvola] WebExtension.vala:130: Window object cleared for 'https://play.spotify.com/radio'
Worker: [DEBUG    Nuvola] WebExtension.vala:140: Init frame: https://play.spotify.com/radio, 0x55d921976130, 0x55d9211d25e0, 0x7f5e9042f740
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix: webkitConvertPointFromPageToNode -> ConvertPointFromPageToNode | function webkitConvertPointFromPageToNode() {\n    [native code]\n}'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix: webkitConvertPointFromNodeToPage -> ConvertPointFromNodeToPage | function webkitConvertPointFromNodeToPage() {\n    [native code]\n}'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix: webkitRequestAnimationFrame -> RequestAnimationFrame | function webkitRequestAnimationFrame() {\n    [native code]\n}'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix: webkitCancelAnimationFrame -> CancelAnimationFrame | function webkitCancelAnimationFrame() {\n    [native code]\n}'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix: webkitCancelRequestAnimationFrame -> CancelRequestAnimationFrame | function webkitCancelRequestAnimationFrame() {\n    [native code]\n}'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Missing hidden: webkitMediaSource -> MediaSource | undefined'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix hidden: webkitAudioContext -> AudioContext | [object webkitAudioContextConstructor]'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix hidden: webkitAudioPannerNode -> AudioPannerNode | [object webkitAudioPannerNodeConstructor]'
Worker: [DEBUG    Nuvola] jsapi.vala:550: Nuvola.log: 'Unprefix hidden: webkitOfflineAudioContext -> OfflineAudioContext | [object webkitOfflineAudioContextConstructor]'
Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded https://play.spotify.com/radio
Runner: Failed to open VDPAU backend libvdpau_va_gl.so: nem nyitható meg a megosztott objektumfájl: Nincs ilyen fájl vagy könyvtár
Runner: https://play.spotify.edgekey.net/client/92de0ed/js/spotify.web.client.js:415:443: CONSOLE LOG Connecting to wss://sto3-linkap-a3.ap.spotify.com:443
Runner: https://play.spotify.edgekey.net/client/92de0ed/js/spotify.web.client.js:415:443: CONSOLE INFO [AppLoader] Using only bundled apps
Runner: https://play.spotify.com/radio:12:11205: CONSOLE ERROR TypeError: null is not an object (evaluating 'player.getPlayerState')
Runner: https://play.spotify.edgekey.net/apps/radio/4.1.20/main.js:13:14199: CONSOLE LOG Success client-log {"event":"user:impression","data":{"app_version":"4.1.20"},"eventVersion":"initial-view"}
Runner: https://play.spotify.edgekey.net/apps/now-playing-recs/2.2.2/kindling.js:3:5713: CONSOLE LOG Success client-log ,user:impression,appStart,,[object Object]
Runner: https://play.spotify.edgekey.net/apps/radio/4.1.20/app/bower_components/jquery/dist/jquery.min.js:3:32146: CONSOLE WARN The page at https://play.spotify.com/radio was allowed to display insecure content from http://o.scdn.co/640/d526f0a800bdb35f3bca12ef41c322f53710bbbe.
```

and:

```
Runner: CONSOLE WARN The page at https://play.spotify.com/radio was allowed to display insecure content from http://o.scdn.co/300/13b6699bbec89263358ce5a2395e7358abd257bd457c8f55549cf491b2d93227907dfdefc5f5f8fea7e8ad44bc07f898c1e1839b0e8e35f08e5029eec0963679788f9479e327aabdbbd36fa4647379f4.

Runner: https://play.spotify.edgekey.net/apps/radio/4.1.20/main.js:13:14199: CONSOLE LOG Success client-log {"event":"info:timer","data":{"err":"none","duration":429},"eventVersion":"cosmos-request:all?language=en"}
Runner: https://play.spotify.edgekey.net/apps/radio/4.1.20/main.js:13:14199: CONSOLE LOG Success client-log {"event":"info:timer","data":{"err":"none","duration":2005},"eventVersion":"cosmos-request:stations/eced45eede77486b9261f941c30c8224/touch"}
Runner: https://play.spotify.edgekey.net/client/92de0ed/js/spotify.web.client.js:415:443: CONSOLE WARN [FB] error
Runner: https://play.spotify.edgekey.net/apps/radio/4.1.20/main.js:13:14199: CONSOLE LOG Success client-log {"event":"user:hit","data":{"target_uri":"spotify:track:1Cz9GFuqKYaqj1XiRm4714","name":"Grace So Glorious"},"context":"now-playing/playing-covers/media-object","eventVersion":"play-button"}
Runner: https://play.spotify.edgekey.net/apps/radio/4.1.20/app/bower_components/jquery/dist/jquery.min.js:3:32146: CONSOLE WARN The page at https://play.spotify.com/radio was allowed to display insecure content from http://o.scdn.co/640/4e4e6e20c632234614dff5a081231e0fc87cf8e6.
```

**Comment by fenryxo** [comment] 2016-06-06 08:28
Hello @regisz. The bug was fixed. Your issue is probably a duplicate of the issue of Spotify script: tiliado/nuvola-app-spotify#10

**Comment by regisz** [comment] 2016-06-06 08:30
I check it, thx
