### ISSUE TITLE
Similar Arist Pictures on Album Pages stretched.

### ISSUE THREAD

**Issue by dd23** [tiliado/nuvolaplayer#72] opened 2015-01-23 11:42 UTC
**This issue is probably caused by a bug in an external library and cannot be fixed in Nuvola Player itself.** The bug report has been forwarded upstream to [the WebKitGTK+ bug tracker](https://bugs.webkit.org/show_bug.cgi?id=140823) and this issue has been added to [the list of known issues](https://github.com/tiliado/nuvola-app-google-play/wiki/Known-Issues).

Reason: It is reproducible in the WebKiGTK+ MiniBrowser debugging tool, so it's likely a bug in the WebKitGTK+ library rather than in Nuvola Player.

*Original report follows:*

If you are on an **album page** and Google Music shows related/similar artists at the bottom, their images are vertically stretched to the full size of the Nuvola Window.

Screenshot:
![nuvola](https://cloud.githubusercontent.com/assets/630500/5873985/17a1d392-a2fd-11e4-95f1-ff9de0a7f42e.png)

The error happens only on album pages. If you look at an artist page, the related artist pictures looks fine.
This problem does not occur, when i visit Google Music with the Chromium browser.

**Comment by fenryxo** [comment] 2015-01-23 15:19
Hi. Thanks for taking the time to report this issue. Is the issue reproducible also in WebKit2Gtk MiniBrowser? Run in terminal:

```
/usr/lib/x86_64-linux-gnu/webkit2gtk-3.0/libexec/MiniBrowser \
http://play.google.com/music
```
or
```
/usr/lib/i386-linux-gnu/webkit2gtk-3.0/libexec/MiniBrowser \
http://play.google.com/music
```

**Comment by dd23** [comment] 2015-01-23 15:24
Yes, the problem also occurs in the 64-bit version of the MiniBrowser.

**Comment by fenryxo** [comment] 2015-01-23 15:33
Then it seems to be a bug in WebKitGTK library and it is necessary to [report this issue upstream](http://webkitgtk.org/) - to the WebKit bugzila - with following information:

* Precise description of the problem.
* Version of the WebKitGtk library.
* Screenshot of the MiniBrowser window.

Are you willing to do that or should I do so?

**Comment by dd23** [comment] 2015-01-23 15:34
I will take care of that, thanks for your help so far :+1:

**Comment by fenryxo** [comment] 2015-01-23 15:36
Ok, please post here a link to the bug report then :-)

**Comment by dd23** [comment] 2015-01-23 16:08
Reported the bug here: 
https://bugs.webkit.org/show_bug.cgi?id=140823

**Comment by fenryxo** [comment] 2015-01-24 14:54
Thanks. I've subscribed myself to the upstream bug report and added this issue to [the list of known issues](https://github.com/tiliado/nuvola-app-google-play/wiki/Known-Issues). Since I cannot do more, I'm closing this bug report for now.

**Closed by fenryxo** 2015-01-24 14:54 UTC
Labels: more info required, upstream
