### ISSUE TITLE
Service request: BBC Iplayer radio streams

### ISSUE THREAD

**Issue by choffee** [tiliado/nuvolaplayer#202] opened 2016-02-05 09:47 UTC
It would be great to have a plugin for the BBC iPlayer web app in the UK.
https://www.bbc.co.uk/radio
##

**Comment by fenryxo** [comment] 2016-02-05 10:33
Hello @choffee. Thanks for your service request. Nuvola Player project operates within a limited budget and [the queue of service integration requests](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3A%22new+service%22+sort%3Acreated-asc) is pretty long. Would you like to support your request financially in order to increase its priority?

**Comment by a-m-s** [comment] 2017-02-02 00:06
I had a look at the iPlayer in Vivaldi and it looked like integrating it into Nuvola it would be easy. However, it turns out that the iPlayer falls back to a flash player when loaded in Epiphany, which makes it hard to get the playing state or click buttons. Is it still possible somehow?

I tried the Epiphany user agent in Vivaldi and still no flash needed, so it's not that that's the problem. Maybe there's a plugin missing? I tried disabling Widevine, but Vivaldi still works.

**Comment by a-m-s** [comment] 2017-02-02 00:16
Hmm, there might be some clues here: http://www.bbc.co.uk/html5

Might be no MSE support?

**Comment by a-m-s** [comment] 2017-02-03 09:33
More clues here: https://www.youtube.com/html5

In Epiphany the Media Source Extensions and MSE boxes are not ticked. I little research suggests that an improved MSE implementation is ongoing in webkit and gstreamer, so maybe it'll work next year. :-(

Integrating the BBC HTML5 player into Nuvola would not be too challenging, but I don't know how to do anything useful with the Flash player.

**Comment by fenryxo** [comment] 2017-02-03 14:32
> In Epiphany the Media Source Extensions and MSE boxes are not ticked. I little research suggests that an improved MSE implementation is ongoing in webkit and gstreamer, so maybe it'll work next year. :-(

MSE support has landed in the WebKit trunk and should be available in the WebKitGTK 2.15.x development build leading to the 2.16.x stable releases. I'm going to build [Nuvola CDK](https://github.com/tiliado/nuvolaplayer/wiki/Nuvola-Core-Developer-Kit) with WebKitGTK 2.15.4 to test MSE with Google Play Music. Should you be interested, I can provide you with instructions how to use Nuvola CDK to test MSE with BBC Player.

**Comment by a-m-s** [comment] 2017-02-03 18:17
I installed 2.15 yesterday but Epiphany continued to use the Flash player on the BBC and report no MSE support on YouTube.

If you can get it to work then I'd be interested in that, yes.

**Comment by fenryxo** [comment] 2017-02-04 06:34
MSE is disabled by default. It must be enabled both in build time and run time.

**Comment by fenryxo** [comment] 2017-02-06 13:13
It took me a whole weekend but [Nuvola CDK](https://github.com/tiliado/nuvolaplayer/wiki/Nuvola-Core-Developer-Kit) with WebKitGTK+ & MSE is ready. I didn't have enough time to test it properly though. I remember there were some GStreamer errors in the console. I'm going to discuss that with upstream at the weekend.

If you want to play, install [Nuvola CDK](https://github.com/tiliado/nuvolaplayer/wiki/Nuvola-Core-Developer-Kit) and set `mse_enabled` in the `metadata.in.json` file of your script.

**Comment by a-m-s** [comment] 2017-02-07 11:07
OK, I tried that. One comment on you instructions first: the -d option requires that I install a dev runtime, but it took me a few minutes to figure out what that meant and how to do it.

With this build I can open the YouTube HTML5 page and it does indeed say that MSE is enabled. (Although plain H264 is no longer available.)

However, the BBC site still uses the Flash player. I'll need more time to figure out why.

**Comment by fenryxo** [comment] 2017-02-07 11:33
> One comment on you instructions first: the -d option requires that I install a dev runtime, but it took me a few minutes to figure out what that meant and how to do it.

Thanks for your feedback. I've updated the instructions. Are other parts clear or it there anything to improve?

> With this build I can open the YouTube HTML5 page and it does indeed say that MSE is enabled. (Although plain H264 is no longer available.)

Maybe a H264 codec is missing.

> However, the BBC site still uses the Flash player. I'll need more time to figure out why.

The test script (`run -a test`) contains a link to MSE test suites. When I ran them, there were a few GStreamer errors in the console. A development version of Gstreamer might be required for MSE to function properly.

**Comment by a-m-s** [comment] 2017-02-07 13:04
Is there anything to change in the webkit build besides adding -DENABLE_MEDIA_SOURCE=ON to the cmake line? Maybe I built my weblit2-gtk-unstable wrong?

**Comment by fenryxo** [comment] 2017-02-07 14:48
I build WebKit with following options:
```
"config-opts": [
                "-DPORT=GTK",
                "-DCMAKE_BUILD_TYPE=Release",
                "-DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG",
                "-DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG",
                "-DENABLE_ACCELERATED_2D_CANVAS=OFF",
                "-DCMAKE_INSTALL_PREFIX:PATH=/app",
                "-DLIB_INSTALL_DIR:PATH=/app/lib",
                "-DSYSCONF_INSTALL_DIR:PATH=/app/etc",
                "-DSHARE_INSTALL_PREFIX:PATH=/app/share",
                "-DINCLUDE_INSTALL_DIR:PATH=/app/include",
                "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON",
                "-DBUILD_SHARED_LIBS:BOOL=ON",
                "-DENABLE_GTKDOC=OFF",
                "-DENABLE_VIDEO=ON",
                "-DENABLE_WEB_AUDIO=ON",
                "-DENABLE_MEDIA_SOURCE=ON"
            ],
```

Then it is necessary to set [WebKitSettings::enable-mediasource](https://webkitgtk.org/reference/webkit2gtk/unstable/WebKitSettings.html#WebKitSettings--enable-mediasource) to `true`.

**Comment by a-m-s** [comment] 2017-02-07 17:30
Sorry for being thick, but where does one set WebKitSettings?

**Comment by fenryxo** [comment] 2017-02-07 19:39
In the source code of a particular WebKitGTK application.

**Comment by a-m-s** [comment] 2017-02-08 00:03
OK, so part of the problem is that mediasource isn't enabled in the nuvola 3.0.4 I have on my system, so it doesn't make any use of my newly build webkit2gtk.

However, inside the flatpak dev environment the www.bbc.co.uk/html5 page now allows me to select the HTML5 player. Previously it just said "Sorry, we can't provide you with the HTML5 player in this browser". However, after "opting in" to html5 it still doesn't actually work. That might be because the H.264 codec is missing? Not sure.

Anyway, I've now built 3.1 and running it against the custom built webkit2gtk the player is working. I can get on with trying to do the integration. :-)

**Comment by fenryxo** [comment] 2017-02-08 13:48
> However, inside the flatpak dev environment the www.bbc.co.uk/html5 page now allows me to select the HTML5 player. Previously it just said "Sorry, we can't provide you with the HTML5 player in this browser". However, after "opting in" to html5 it still doesn't actually work. That might be because the H.264 codec is missing? Not sure.

I'm going to add the H264 codec to the flatpaks (#294)

> Anyway, I've now built 3.1 and running it against the custom built webkit2gtk the player is working. I can get on with trying to do the integration. :-)

Great! Happy hacking :-)

**Comment by fenryxo** [comment] 2017-02-12 14:36
> I'm going to add the H264 codec to the flatpaks (#294)

Done:

![bbc_html5](https://cloud.githubusercontent.com/assets/853706/22862960/9253330c-f138-11e6-8fcb-897b335ab700.png)
![youtube_html5](https://cloud.githubusercontent.com/assets/853706/22862980/ed8d212e-f138-11e6-9bfb-3c1ae372010e.png)

**Comment by a-m-s** [comment] 2017-02-13 13:47
I updated the flatpak (new name gotcha'd me) updated Diorite and Nuvola, followed the instructions again, and now I get a build failure.

```
Build failed
 -> task in 'nuvolaplayer3-runner' failed (exit status 1): 
	{task 139686099333248: valac ApiBus.vala,AppRunnerController.vala,Flatpak.vala,MasterBus.vala,MasterController.vala,ActionsBinding.vala,Binding.vala,Bindings.vala,LauncherBinding.vala,MediaKeysBinding.vala,MediaPlayerBinding.vala,MenuBarBinding.vala,NotificationBinding.vala,NotificationsBinding.vala,PasswordManagerBinding.vala,Component.vala,ComponentsManager.vala,WebApp.vala,WebAppRegistry.vala,WebAppStorage.vala,WebAppWindow.vala,WebWorker.vala,FormatSupport.vala,FormatSupportCheck.vala,FormatSupportDialog.vala,AboutDialog.vala,NetworkSettings.vala,PreferencesDialog.vala,Sidebar.vala,WelcomeWindow.vala,ActionsInterface.vala,MediaKeysInterface.vala,MenuBarInterface.vala,NotificationInterface.vala,NotificationsInterface.vala,AppRunner.vala,LauncherModel.vala,MediaPlayerModel.vala,Connection.vala,Desktop.vala,NetworkManager.vala,Oauth2Client.vala,TiliadoAccountWidget.vala,TiliadoApi2.vala,JsonReader.vala,AppCategoriesView.vala,WebAppListFilter.vala,WebAppListModel.vala,WebAppListView.vala,WebAppListWindow.vala,WebEngine.vala,WebView.vala,WebWindow.vala,ActionsHelper.vala,DeveloperComponent.vala,DeveloperSidebar.vala,HttpRemoteControlAppRequest.vala,HttpRemoteControlChannel.vala,HttpRemoteControlComponent.vala,HttpRemoteControlRequestContext.vala,HttpRemoteControlServer.vala,ActionsKeyBinder.vala,ActionsKeyBinderClient.vala,ActionsKeyBinderServer.vala,GlobalActionsKeyBinder.vala,GlobalKeyBinder.vala,GlobalKeyBindings.vala,KeybindingsSettings.vala,XKeyGrabber.vala,AZLyricsFetcher.vala,LyricsComponent.vala,LyricsFetcher.vala,LyricsFetcherCache.vala,LyricsProvider.vala,LyricsSidebar.vala,MediaKeyClient.vala,MediaKeyServer.vala,MediaKeys.vala,MediaKeysComponent.vala,MediaPlayer.vala,Menubar.vala,MPRISApplication.vala,MPRISComponent.vala,MPRISPlayer.vala,MPRISProvider.vala,Notifications.vala,NotificationsComponent.vala,PasswordManager.vala,PasswordManagerComponent.vala,AudioScrobbler.vala,AudioScrobblerComponent.vala,LastfmCompatibleScrobbler.vala,LastfmScrobbler.vala,ScrobblerSettings.vala,TrayIcon.vala,TrayIconComponent.vala,UnityLaucher.vala,UnityLauncherComponent.vala,secret.vapi -> nuvolaplayer3-runner.h,nuvolaplayer3-runner.vapi,nuvolaplayer3-runner.deps,ApiBus.c,AppRunnerController.c,Flatpak.c,MasterBus.c,MasterController.c,ActionsBinding.c,Binding.c,Bindings.c,LauncherBinding.c,MediaKeysBinding.c,MediaPlayerBinding.c,MenuBarBinding.c,NotificationBinding.c,NotificationsBinding.c,PasswordManagerBinding.c,Component.c,ComponentsManager.c,WebApp.c,WebAppRegistry.c,WebAppStorage.c,WebAppWindow.c,WebWorker.c,FormatSupport.c,FormatSupportCheck.c,FormatSupportDialog.c,AboutDialog.c,NetworkSettings.c,PreferencesDialog.c,Sidebar.c,WelcomeWindow.c,ActionsInterface.c,MediaKeysInterface.c,MenuBarInterface.c,NotificationInterface.c,NotificationsInterface.c,AppRunner.c,LauncherModel.c,MediaPlayerModel.c,Connection.c,Desktop.c,NetworkManager.c,Oauth2Client.c,TiliadoAccountWidget.c,TiliadoApi2.c,JsonReader.c,AppCategoriesView.c,WebAppListFilter.c,WebAppListModel.c,WebAppListView.c,WebAppListWindow.c,WebEngine.c,WebView.c,WebWindow.c,ActionsHelper.c,DeveloperComponent.c,DeveloperSidebar.c,HttpRemoteControlAppRequest.c,HttpRemoteControlChannel.c,HttpRemoteControlComponent.c,HttpRemoteControlRequestContext.c,HttpRemoteControlServer.c,ActionsKeyBinder.c,ActionsKeyBinderClient.c,ActionsKeyBinderServer.c,GlobalActionsKeyBinder.c,GlobalKeyBinder.c,GlobalKeyBindings.c,KeybindingsSettings.c,XKeyGrabber.c,AZLyricsFetcher.c,LyricsComponent.c,LyricsFetcher.c,LyricsFetcherCache.c,LyricsProvider.c,LyricsSidebar.c,MediaKeyClient.c,MediaKeyServer.c,MediaKeys.c,MediaKeysComponent.c,MediaPlayer.c,Menubar.c,MPRISApplication.c,MPRISComponent.c,MPRISPlayer.c,MPRISProvider.c,Notifications.c,NotificationsComponent.c,PasswordManager.c,PasswordManagerComponent.c,AudioScrobbler.c,AudioScrobblerComponent.c,LastfmCompatibleScrobbler.c,LastfmScrobbler.c,ScrobblerSettings.c,TrayIcon.c,TrayIconComponent.c,UnityLaucher.c,UnityLauncherComponent.c}
''
```

**Comment by fenryxo** [comment] 2017-02-13 14:01
Interesting. Could you save a complete output to a file and attach it here?

**Comment by a-m-s** [comment] 2017-02-13 14:26
[build.log.txt](https://github.com/tiliado/nuvolaplayer/files/771321/build.log.txt)

**Comment by fenryxo** [comment] 2017-02-13 14:41
My fault. I forget to push the last diorite commit. You can no pull & build Diorite and then Nuvola.

**Comment by a-m-s** [comment] 2017-02-13 14:45
Better, but the build still fails. :-(

[build.log.txt](https://github.com/tiliado/nuvolaplayer/files/771361/build.log.txt)

**Comment by fenryxo** [comment] 2017-02-13 16:08
Hm, that need more time to investigate. It's time to create an always-functional stable branch and do experiments only in the master branch.

**Comment by a-m-s** [comment] 2017-02-13 16:37
The good news is that I have the integration working for iPlayer TV and radio. It also does warning messages to guide the user to the opt in page. I want to add integration for news clips (because they're easy to navigate to from iPlayer and why not), but then it'll be pretty much done and ready to wait for the dependencies to catch up.

**Comment by a-m-s** [comment] 2017-02-13 16:53
My work-in-progress is here: https://github.com/a-m-s/nuvola-app-bbc-iplayer

**Comment by fenryxo** [comment] 2017-02-15 17:10
> It also does warning messages to guide the user to the opt in page.

It might not be necessary. What happens if you just set `"flash_enabled" : false` in metadata.in.json? BBC could just switch to HTML5 player automatically.

> My work-in-progress is here: https://github.com/a-m-s/nuvola-app-bbc-iplayer

Awesome. I'll look into it as soon as the CDK/ADK with the upgraded GStreamer works.

**Comment by a-m-s** [comment] 2017-02-15 17:24
I think it automatically uses HTML5 where it thinks the browser is good enough, but does not enable it automatically if the browser is borderline somehow, even when Flash is not available.

It gives the "you need flash" message instead of any video. I suppose that makes sense if the browser's HTML5 support is very wonky.

I say "I think" because I did that test a little while ago now, with the old webkit. I'll test this again when I get a working nuvola-dev build again (I should have kept the old one).

**Comment by fenryxo** [comment] 2017-02-17 11:28
> I say "I think" because I did that test a little while ago now, with the old webkit.

Well, there has been a lot of changes since then - WebKitGTK/GStreamer with MSE. Could you test again:

  * Add `"flash_enabled" : false` to metadata.in.json
  * Run your script inside [Nuvola ADK](https://github.com/tiliado/nuvolaplayer/wiki/Nuvola-App-Developer-Kit) (yes, another *DK, this one shoulf be more convenient for script maintainers)

To be sure there isn't any cache/configuration left, it may be necessary to run also 

```
cd ~/.var/app/eu.tiliado.NuvolaAdk
rm -rf .adobe cache config .config data .local .macromedia
```

**Comment by fenryxo** [comment] 2017-02-17 19:01
FYI, there are now the master and stable branches. Only the master branch supports MSE.

**Comment by a-m-s** [comment] 2017-02-17 23:27
I installed the master ADK flatpak, but I think I might have misconfigured something because I got this message and then just nuvola closes.

![screenshot from 2017-02-17 23-24-03](https://cloud.githubusercontent.com/assets/5088295/23086989/85398aac-f568-11e6-80af-8e57f9812b5d.png)

**Comment by fenryxo** [comment] 2017-02-18 07:28
Well, the error message certainly needs to be improved to be more clear what to do with that. You need to [install Flatpak's XDG Desktop Portal API](https://github.com/tiliado/nuvolaplayer/wiki/Flatpaks#step-1-install-flatpak). The package names should be `xdg-desktop-portal` and `xdg-desktop-portal-gtk`.

**Comment by a-m-s** [comment] 2017-02-18 15:49
Ah, OK, I assumed it was something inside the flatpak. Fixed now.

**Comment by a-m-s** [comment] 2017-02-18 17:39
I think my project is now done. The repo is [here](https://github.com/a-m-s/nuvola-app-bbc-iplayer). As far as I know, all the different flavours of content now integrate with play/pause/toggle.

I've set the minimum API to 3.1, for MSE support. That doesn't fix third party packages, of course, but hopefully your flatpaks will be alright?

The BBC site does, in fact, auto-select HTML5 when flash is disabled, but I've left Flash enabled because there is still some content for which the BBC only supports Flash (live sport, etc., apparently), and I think it's better for it to work without integration than to not work at all. For that reason the pop-up guidance remains, although I've cleaned it up a little.

The HTML5 support in your flatpak is much more stable than what I built. The content sometime freezes, but it's usable.

You'll probably have difficulty testing the iPlayer-proper from outside the UK, but you can probably try the videos on the news site. Actually, it would be good if you did, because I can't test that the international service works the same or not (I know the BBC add advertising for international visitors, and who knows what that breaks).

**Comment by fenryxo** [comment] 2017-02-20 09:23
Hello @a-m-s. You won't like me but I've just broken your script again. The specification of app requirements has changed and hopefully for good. In short:

  * Remove `flash_enabled` and `mse_enabled` as they don't have any effect anymore.
  * Add the `requirements` field containing `WebKitGTK[2.15.3] Codec[MP3] Codec[H264] Feature[MSE] Feature[Flash]`

The plan is as follows:

  * You'll add the `requirements`.
  * I'll review and test your script.
  * I'll create a flatpak in the master branch.
  * I'll announce your script.
  * WebKitGTK+ releases 2.16.0.
  * GStreamer releases 1.12.0.
  * I'll enable MSE in the stable flatpaks.
  * I'll push your flatpak to the stable branch.

**Comment by a-m-s** [comment] 2017-02-20 13:58
Changes done.

**Comment by fenryxo** [comment] 2017-03-12 19:34
Hello @a-m-s. Great :-) Could you [transfer the repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) to the [Nuvola Maintainers](https://github.com/orgs/tiliado/teams/nuvola-maintainers) team? You will be still the main maintainer.

I've tested BBC World Service and it works. However, I've noticed one minor issue to fix: Either the play or the pause button must be active, not both. 

![bbc iplayer_141](https://cloud.githubusercontent.com/assets/853706/23835182/31faf27e-0763-11e7-9c2f-fb0518fc0e72.png)

**Comment by fenryxo** [comment] 2017-03-12 19:36
The eu.tiliado.NuvolaAppBbcIplayer//master flatpak has been uploaded to the flatpak repository.

**Comment by fenryxo** [comment] 2017-03-12 19:43
Also, could you register at Tiliado.eu and post here your username to get a developer account? 3.1 Rolling Releases are currently available only to developers and patrons.

**Comment by a-m-s** [comment] 2017-03-13 12:24
Done, username: ams

**Comment by a-m-s** [comment] 2017-03-13 12:33
It doesn't seem to be possible to transfer the repo to a team (or I lack the necessary github-fu). I've transferred it to tiliado. I think you have to add it to the team?

**Comment by a-m-s** [comment] 2017-03-13 13:01
Fixed the play/pause issue.

**Comment by fenryxo** [comment] 2017-03-13 14:07
Great. Welcome aboard! Please subscribe to the [Nuvola Player Development mailing list](https://groups.google.com/forum/#!forum/nuvola-player-devel) not to miss any important announcements.

I've just tagged the 1.1 release. When WebKitGTK+ releases 2.16.0 and GStreamer releases 1.12.0, the script will be pushed to the stable flatpak repo and properly announced.

**Closed by fenryxo** 2017-03-13 14:07 UTC
Labels: in progress, new service, reply, wishlist

**Comment by a-m-s** [comment] 2017-03-13 14:33
Thanks for setting up the account. I can confirm that the flatpak iplayer works for me. :-)

**Comment by fenryxo** [comment] 2017-04-13 08:18
Follow-up: #321
