### ISSUE TITLE
Spotify, Ubuntu 16.04: Unity: Error during call of Nuvola.actions.emit: Function 'Nuvola.actions.emit' failed.

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaplayer#298] opened 2017-02-13 07:16 UTC
About for 3-4 weeks I get the next error message:

Error during call of Nuvola.actions.emit: Function 'Nuvola.actions.emit' failed. https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9: TypeError: _flashObject.getSWF().sp_pause is not a function. (In '_flashObject.getSWF().sp_pause(id)', '_flashObject.getSWF().sp_pause' is undefined)

The application might not function properly.

And the WebKitPluginProcess2 crashed.

**Comment by fenryxo** [comment] 2017-02-13 08:30
Hello @regisz. Thanks for taking the time to report your issue. I need more information to investigate it further. Could you provide me with the Basic information from [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#basic-information)?

**Comment by regisz** [comment] 2017-02-13 09:53
Hello @fenryxo 
Yes, of course :).

- I start Spotify.
- After I pause playing with my keyboard button, then I get a popup window with the error message.
- And the "Spotify" menu item is renamed to "Unknown application name".
- And WebKitPluginProcess crashed.

__$ lsb_release -a__
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

__$ nuvola --version__
Nuvola Apps 3.1.1+201702122007.7eb4cf2
Revision 7eb4cf27a8156b24f77af8bfc59c4f262702ae22
Diorite 0.3.1+201702120020.0cdf09c
WebKitGTK 2.14.3
libsoup 2.52.2

__Attachments:__
![nuvolaplayer3 - error window](https://cloud.githubusercontent.com/assets/5145946/22876816/bda13b9a-f1d2-11e6-93dd-c41b9b081926.png)

![nuvolaplayer3 - unknown application name menu item](https://cloud.githubusercontent.com/assets/5145946/22876826/c5142b4e-f1d2-11e6-8528-037f5005e452.png)

[nuvolaplayer3_log.zip](https://github.com/tiliado/nuvolaplayer/files/770496/nuvolaplayer3.zip)

[_usr_lib_x86_64-linux-gnu_webkit2gtk-4.0_WebKitPluginProcess2.1000.zip](https://github.com/tiliado/nuvolaplayer/files/770516/_usr_lib_x86_64-linux-gnu_webkit2gtk-4.0_WebKitPluginProcess2.1000.zip)

**Comment by fenryxo** [comment] 2017-02-13 10:30
It seems to be practically the same issue as in #278. The new Flash 24 crashes resulting in JavaScript errors. I still haven't figured out a way to make this new version of Flash more stable. Is the issue reproducible also in [flatpak builds](https://github.com/tiliado/nuvolaplayer/wiki/Flatpaks)?

**Comment by regisz** [comment] 2017-02-13 12:51
I tried flatpak, but the issue was happened.

**Comment by fenryxo** [comment] 2017-02-13 14:17
Just to be sure you are actually running the flatpak, if you click Spotifi → About, is there "Nuvola Apps (Flatpak Edition)". If Nuvola is lauched from a desktop file, I'm not sure whether the native or the flatpak version has priority.

**Comment by regisz** [comment] 2017-02-13 14:48
No, there is "unsandboxed" but I start it with "flatpak run eu.tiliado.NuvolaAppSpotify " command. And, somewhy now the app would like to install adobe flash player after I started it.

**Comment by fenryxo** [comment] 2017-02-13 15:01
Oh, sorry, I forgot to emphasize that it is necessary to close all Nuvola instances before launching the flatpak. Otherwise, `flatpak run eu.tiliado.NuvolaAppSpotify` just pops up Nuvola from the background.

1. Make sure all Nuvola instances are closed. To be sure, open System Monitor application and look for processes "nuvolaplayer3" and "apprunner".
2. Then run `flatpak run eu.tiliado.NuvolaAppSpotify` and check that the About dialog says "Flatpak Edition)
3. Finally, check whether the issue occurs.

**Comment by regisz** [comment] 2017-02-13 15:08
I checked it, a no any instances ran, but the case is the same and the same nuvolaplayer version.
But, now no flash problem, but the "Unknown" menu can be seen immediately (I did not push any buttons).

**Comment by fenryxo** [comment] 2017-02-23 09:52
Hello @regisz. Right now, I have no idea how to make the Flash plugin more stable in Nuvola. I'll probably have to report bug to the Flash bug tracker to get more clues. Thanks for all your feedback though.

**Comment by regisz** [comment] 2017-02-23 09:55
Ok, I'm waiting for the solution because now I can not use the Nuvola :(.

**Comment by fenryxo** [comment] 2017-04-20 08:31
Hello @regisz. The flatpak build now used WebKitGTK 2.16.1 and Flash 25. Could you check whether the issue is still reproducible?

**Comment by regisz** [comment] 2017-04-20 08:54
Hello @fenryxo . I tried it, but I got the next error:

![flatpak error 2](https://cloud.githubusercontent.com/assets/5145946/25221986/5c2ec864-25b7-11e7-9d4e-9ae8dfc24618.png)

![flatpak error](https://cloud.githubusercontent.com/assets/5145946/25221804/b6f05a52-25b6-11e7-8f75-d7df97470cd9.png)

> $ flatpak -v run eu.tiliado.NuvolaAppSpotify
> XA: No installations directory in /etc/flatpak/installations.d. Skipping
> XA: Allowing dri access
> XA: Allowing x11 access
> XA: Allowing wayland access
> XA: Allowing pulseaudio access
> XA: Allowing session-dbus access
> XA: Allowing system-dbus access
> XA: Running '/usr/lib/flatpak/flatpak-bwrap --args 15 /usr/lib/flatpak/flatpak-dbus-proxy --fd=16 unix:abstract=/tmp/dbus-CuPkz8M2OR /run/user/1000/.dbus-proxy/session-bus-proxy-0V15YY'
> Timeout was reached
> Gtk-Message: Failed to load module "unity-gtk-module"
> $

**Comment by fenryxo** [comment] 2017-04-20 10:59
As the error message says, XDG portal has to be installed. I forgot to mention that we have [new detailed installation instructions for flatpak builds](https://nuvola.tiliado.eu/#!nuvola!ubuntu!).

**Comment by regisz** [comment] 2017-04-20 12:39
I see, I did it, and now I think nuvola works. But I get the next logs:

> $ flatpak run eu.tiliado.NuvolaAppSpotify
> Gtk-Message: Failed to load module "unity-gtk-module"
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: not a number
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: Expected a string.
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:10: not a number
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: not a number
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: Expected a string.
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: nautilus.css:55:71: Using one color stop with linear-gradient() is deprecated.
> 
> (nuvola-app-spotify:2): Gtk-WARNING **: Theme parsing error: nautilus.css:56:71: Using one color stop with linear-gradient() is deprecated.
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: not a number
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: Expected a string.
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:10: not a number
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: not a number
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: Expected a string.
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: nautilus.css:55:71: Using one color stop with linear-gradient() is deprecated.
> 
> (eu.tiliado.NuvolaAppSpotify:2): Gtk-WARNING **: Theme parsing error: nautilus.css:56:71: Using one color stop with linear-gradient() is deprecated.

Is this ok?

**Comment by fenryxo** [comment] 2017-04-20 13:09
The flatpak build contains Ambiance theme from Ubuntu 16.10, which is not 100% compatible with GTK+ 3.22. I should update it to that from Ubuntu 17.04. Re-ticketed as #324.

Anyway, I'm closing this issue as you think Nuvola works but feel free to report back if the issue occurs again.

**Closed by fenryxo** 2017-04-20 13:09 UTC
Labels: bug

**Comment by regisz** [comment] 2017-04-20 13:13
Ok, @fenryxo
