### ISSUE TITLE
I can't write accented words in Spanish

### ISSUE THREAD

**Issue by munix** [tiliado/nuvolaplayer#535] opened 2019-06-16 04:35 UTC
- Your Linux distribution and its version: Mint 19.1

- Your desktop environment: Cinnamon

- Nuvola Runtime version: 4.16.10 (10-gb11d0c4)

 - The web app you use and its version: Google Keep Script

### Describe the bug

When I write notes in Google Keep through the Nuvola app I can't use the key combination that gives me accented letters like "aéíóú". However, if I can use the letter "ñ".
In the browser if it works correctly
The most curious thing is that as the Google account and system configuration are in Spanish, the spell checker underlines me the word as misspelled

**Steps to reproduce the behavior**

1. I open a new card or an existing card
2. I write as usual using the combination of keys (see attached photo) in order to obtain an accented letter.

**Expected behavior**

I want to be able to properly write words like "música" but I get "musica"

**Debugging log**

Attached

**Screenshots**

Attached

[nuvola_keep_log.txt](https://github.com/tiliado/nuvolaruntime/files/3293823/nuvola_keep_log.txt)

![photo](https://user-images.githubusercontent.com/33894751/59559104-da659180-9000-11e9-8317-78a4333beaae.png)

**Comment by fenryxo** [comment] 2019-06-17 09:19
Hello @minix. Thanks for reporting the issue. It looks as if the `´` key was entirely ignored.

> The most curious thing is that as the Google account and system configuration are in Spanish, the spell checker underlines me the word as misspelled

Reticketed as tiliado/nuvolaruntime#537.

**Comment by emanuelbatista** [comment] 2019-07-22 02:52
I'm with that issue also in Portuguese.

**Comment by munix** [comment] 2019-07-22 09:01
> I'm with that issue also in Portuguese.

Let's force them to see if they can fix it. It is useless to work like this

**Comment by a-m-s** [comment] 2019-07-22 10:05
I can confirm that accented characters on a UK keyboard don't work either (e.g. "AltGr+; e" usually gives é, but not in a Nuvola window). Not that this is a great loss in English, of course.

Possibly the flatpak version of gtk is configured for a different keyboard layout? I know the standard US keyboard has no way to write those characters ("US Intl" does). However, shift+2 gives " as it should on a UK layout, so it's not quite that simple.

**Comment by fenryxo** [comment] 2019-07-22 16:45
> Possibly the flatpak version of gtk is configured for a different keyboard layout?

GTK is ok. The issue is in Chromium Embedded Framework.

**Comment by fenryxo** [comment] 2020-10-27 15:10
This will be fixed in the QtWebWengine port of Nuvola in #583. The work-in-progress components [Wayland Embedded View Framework Server](https://github.com/tiliado/wayland-embedded-view-server) and [Wayland Embedded View Framework Client](https://github.com/tiliado/wayland-embedded-view-client) use the basic GTK+ 3 IM context to support dead keys (`´` + `a` = `á`, etc.).

**Comment by jiri-janousek** [comment] 2022-01-08 08:40
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.

**Closed by jiri-janousek** 2022-01-08 08:40 UTC
Labels: type: bug, QtWebEngine port
