### ISSUE TITLE
Google Play Music queue does not scroll

### ISSUE THREAD

**Issue by leehblue** [tiliado/nuvolaplayer#206] opened 2016-02-09 19:40 UTC
Using Linux Mint 17.3 the Google Play Music queue of songs does not scroll. If the number of songs in the queue is more than can be shown, it is not possible to scroll view. Here is an image showing the problem.
![google-play-queue](https://cloud.githubusercontent.com/assets/960432/12928367/1020d3d2-cf3b-11e5-9316-0be6e826c88c.png)

**Comment by fenryxo** [comment] 2016-02-10 10:45
Hello. Thanks for reporting this issue. Since the issue is reproducible also in the WebKitGtk 2.4.8 MiniBrowser (see tiliado/nuvola-app-google-play-music#10) and I cannot reproduce it with a newer WebKitGtk (2.6.2 in Debian Jessie), I believe Google Play Music simply requires a newer WebKitGTK than 2.4.8 available in Ubuntu 14.04/elementary OS Freya.

I've added a new entry to Known issues ([Scrolling through the playlist queue doesn't work with WebKitGtk 2.4.8](https://github.com/tiliado/nuvola-app-google-play-music/wiki/Known-Issues#scrolling-through-the-playlist-queue-doesnt-work-with-webkitgtk-248)) and I'm closing this ticket as an upstream issue. I'm sorry I cannot do more.

**Closed by fenryxo** 2016-02-10 10:45 UTC
Labels: bug, upstream

**Comment by fenryxo** [comment] 2016-04-16 19:49
The repository of **the Nuvola Player 3.1 Rolling Releases** now contains the WebKitGTK 2.8.5 packages for Ubuntu 14.04 and Nuvola Player packages for this distribution have been rebuilt to use them instead of the old WebKitGTK packages provided by Ubuntu. **This should fix all rendering/integration issues that had occurred only in Ubuntu 14.04.** Nuvola Patrons and other people with access to the rolling releases are welcome to try them out. If no problems are found, same trick will be made also for Nuvola Player 3.0 Stable Releases eventually (#216).

**Comment by fenryxo** [comment] 2016-04-30 06:35
The repository of **the Nuvola Player 3.0 Stable Releases** now contains the WebKitGTK 2.8.5 packages for Ubuntu 14.04 and Nuvola Player 3.0.2 packages for this distribution have been built to use them instead of the old WebKitGTK packages provided by Ubuntu. **This should fix all rendering/integration issues that had occurred only in Ubuntu 14.04.**
