### ISSUE TITLE
nuvolaplayer3 crashes on Fedora 25

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaplayer#283] opened 2017-01-20 08:44 UTC
installed nuvolaplayer (own compiled package) 
nuvolaplayer-3.0.4-1.fc25.x86_64
diorite-devel-0.2.0-1.fc25.x86_64
diorite-0.2.0-1.fc25.x86_64

attached is the backtrace:
[nuvolaplayer-backtrace.txt](https://github.com/tiliado/nuvolaplayer/files/718836/nuvolaplayer-backtrace.txt)

**Comment by fenryxo** [comment] 2017-01-20 16:01
Hello @martinkg. Thanks for taking the time to report this issue. It is a duplicate of tiliado/nuvolaplayer#197, which has been fixed in Diorite 0.2.1. Please upgrade the Diorite library on your system.

**Closed by fenryxo** 2017-01-20 16:01 UTC
