### ISSUE TITLE
Volume fluctuates with any "action" performed in google-chrome

### ISSUE THREAD

**Issue by stellarhopper** [tiliado/nuvolaplayer#85] opened 2015-03-23 22:45 UTC
I'm running Nuvola player on Fedora 21 [1]
While playing music on Google Play Music, if I bring Chrome into focus, sometimes the music volume drops by about 50%. (I think opening a new tab almost certainly provokes this).
Neither of the System or Nuvola/GPM volume sliders appear to have changed position.
Switching back to a different application restores the volume after about 15-20 seconds.
Plugin info from Nuvola [2].

[1] 
Installed Packages
nuvolaplayer3.x86_64                            3.0.0~201502121939.0365088-1.fc21          @nuvola-player
nuvolaplayer3-all-services.x86_64               0.20150209-1.fc21                          @nuvola-player
nuvolaplayer3-google-play-music.x86_64          5.0-1.fc21                                 @nuvola-player

[2]
![nuvola_plugins](https://cloud.githubusercontent.com/assets/1069335/6792241/c4ca0aba-d17b-11e4-9736-1828facabe3d.png)

**Comment by stellarhopper** [comment] 2015-03-23 22:56
Update after more observation:

Any "action" in chrome causes the volume to drop. Opening a link from another application, where it gets opened in chrome in the background also triggers it. After the ~15 second period, even if chrome is in the foreground, the volume does get restored, till you, say, refresh a page..

**Comment by fenryxo** [comment] 2015-03-26 18:45
Hi. Thanks for taking the time to report this really interesting and mysterious issue. I need more information to investigate it further.

First of all, I need to know whether the issue is reproducible in another WebKit2GTK+ browser. Could you install GNOME Web Browser (Epiphany) and check whether the issue is reproducible there?

**Comment by stellarhopper** [comment] 2015-03-26 18:59
@fenryxo Do you mean play google-play-music in epiphany, and do the same steps in chrome, or play music with nuvola, and try to do things in epiphany?

**Comment by fenryxo** [comment] 2015-03-26 19:03
Play google-play-music in epiphany, and do the same steps in chrome :-)

**Comment by stellarhopper** [comment] 2015-03-26 19:06
Yes, it reproduces exactly in epiphany also :)

**Comment by stellarhopper** [comment] 2015-03-27 21:42
I could reproduce this with Youtube also.
Reported at gnome BZ:
https://bugzilla.gnome.org/show_bug.cgi?id=746913

**Comment by fenryxo** [comment] 2015-05-06 16:31
Hi. I've subscribed myself to your bug report at GNOME Bugzilla and closing this bug report here as it seems to be an upstream issue.

**Closed by fenryxo** 2015-05-06 16:31 UTC
